### ISSUE TITLE
Reorganize the Profile solution into multiple projects using typical clean architecture

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-profile#194]
### Description

Split in multiple modules/sub-modules and a repository-project (DbTools++). 

Sperarate projects for: Repository, Integration, Core and API

See the repos of Notifications or Registry for inspiration.

### Tasks

- [ ] Reorganize solution into src and tests

### Acceptance Criterias

- [ ] The Profile solution has  projects, each covering one area of clean architecture.

**Comment by hggutvik** [comment]
Using [Clean Architecture with ASP.NET Core 8 | .NET Conf 2023](https://www.youtube.com/watch?v=yF9SwL0p0Y0&t=1114s) and [this Medium article](https://medium.com/@DrunknCode/clean-architecture-simplified-and-in-depth-guide-026333c54454) as references, the "Infrastructure" project/layer (called _Integrations_ in this repo) seems to be appropriate for holding all data access implementations, including repositories, caching, and clients external APIs,

From this, we are deciding to move the service class implementations as well as the caching from the current project Core to Integrations

**Comment by SandGrainOne** [comment]
Refactoring requires regression testing and I put my trust in the automated tests.
