### ISSUE TITLE
Get KRR credentials

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-profile#195]
Get and check the KRR credentials and if any additional steps are needed (e.g. open any FW/IP filters):

- [ ] Aquire credentials
- [ ] Test the validity from Altinn 3 environments.

**Comment by hansdragnes** [comment]
TSHageland; REST, Token, pointers to code.

**Comment by olebhansen** [comment]
Closing, as this taks cannot progress withouth the actual implementation (#187). I've added my findings in the implementation-task and have clarified what was needed (AFAIK) :-)
