### ISSUE TITLE
Explore what metrics/alarms are valuable

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-profile#196]
Task is a timebox to explore what are default from the platform, and what/how/if we can do better (e.g. if Grafana & co is the future).

I think there are two main usecases we need to cover, with a few common questions to answer. Scenarios:
* The KRR synch has an outage. 
* Our consumers experience issues.

Questions:
* How do we learn about this?
* How do we go about finding the reason so we can take actions within our domain (restart, escalate networking issues, refresh expired credentials) or rule out our involvement and create/transfer the ticket to a more aproperiate team?
* What do we get out of the box?
* See what Platform team has and how they have used it
* Get an ide of how long time it takes to make custom dashboards

While this task is centered on KRR, its output will provide relevant guidelines and/or learning experiences for other Core components as well (both current and future).

### Acceptance criteria:
- [ ] Internal knowledge transfer
- [ ] ADR on what to implement for KRR (the ADR should follow [the format used by the architecture team](https://github.com/Altinn/altinn-decision-log/issues?q=is%3Aopen+is%3Aissue))

**Comment by hggutvik** [comment]
FYI, I moved the "relevance for other components" part out of the acceptance criteria, as this seems more appropriate as part of the context description.

Other good things to know:
- Sebastian Duran of the Platform team is a good person to contact for this task.
- [the following ADR from the Altinn Decision Log](https://github.com/Altinn/altinn-decision-log/issues/3) provides highly relevant material and reasoning
