### ISSUE TITLE
Initiate manual load of KRR in TT+PROD, 2 tasks (before merge & deploy of the PR from Thomas the following week)

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-profile#263]
- TT02
  - [x] Start trigger
  - [x] Verify loading  
- Prod
  - [x] Start trigger
  - [x] Verify loading

**Comment by hggutvik** [comment]
[PR created to supply ChangesLogEndpoint in prod with correct value](https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/1142)

**Comment by hggutvik** [comment]
We need to wait with continuing the prod sync until after tomorrow morning, ref. https://digdir.slack.com/archives/C07MXNNBTUZ/p1732787259051229

**Comment by hggutvik** [comment]
Job (re)initiated in prod today at 12.30. Seems to be running OK

**Comment by hggutvik** [comment]
Verified now that 215 million changes have been replayed, and almost 5,7 million users loaded. Last changes were exported 2024-11-29 18:45
