### ISSUE TITLE
Profile migration: Implement GUI for listing and managing general profile information

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-profile#89]
### Description

Profil portal: Støtte for editering, visning og uthenting av annen profilinformasjon (e.g. språkvalg)

### Description
Currently, in Altinn 2 it is possible to set preferences on ones user profile e.g. language selection and favorite party. 
The new platform must continue this support and migrate existing profile information.

**Comment by olebhansen** [comment]
Closing - GUI work is about to be re-planned by Arbeidsflate
