### ISSUE TITLE
Include the "reservasjon" field from KRR in the profile response

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/altinn-profile#90]
### Description

In order to implement https://github.com/Altinn/app-lib-dotnet/issues/124 we need the "reservasjon" field from KRR in order to decide if we are allowed to create an app instance for a user or not. Currently today, this information is not available on the response.

### Additional Information

This requires a change in Altinn 2 as well as SBLBrigde api's. The issue is part of feature-complete in Altinn 3 and is something that needs to be done. The other alternative is to wait for the profile information to be migrated from Altinn 2 to Altinn 3 and include the field then.

An issue on the Altinn 2 side has been created as well: https://dev.azure.com/digdir/Altinn/_workitems/edit/63696

**Comment by acn-sbuad** [comment]
This is solved by #132 and can be applied in the application if Altinn.Platform.Models is bumped to v. 1.5.0. FYI @RonnyB71
